# Generated by Django 4.2.1 on 2023-05-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNONCE_ID', models.IntegerField()),
                ('FROM_SITE', models.CharField(max_length=255)),
                ('ANNONCE_DATE', models.CharField(max_length=255)),
                ('TYPE', models.CharField(max_length=255)),
                ('NOM', models.CharField(max_length=255)),
                ('ADRESSE', models.CharField(max_length=255)),
                ('CP', models.CharField(max_length=255)),
                ('VILLE', models.CharField(max_length=255)),
                ('ANNONCE_TEXT', models.CharField(max_length=255)),
                ('NB_ETAGE', models.IntegerField()),
                ('SURFACE_TOTAL', models.IntegerField()),
                ('SURFACE_HABITABLE', models.IntegerField()),
                ('NB_VOITURE', models.IntegerField()),
                ('NB_PIECE', models.IntegerField()),
                ('PRIX', models.CharField(max_length=255)),
                ('ANNEE_CONSTRUCTION', models.CharField(max_length=255)),
                ('ANNONCE_LINK', models.CharField(max_length=255)),
            ],
        ),
    ]
